version: '3.8'

services:
  db:
    image: postgres:15
    container_name: credit_db
    environment:
      - POSTGRES_DB=credit_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: credit_redis

  web:
    build: .
    container_name: credit_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=credit_db
      - DB_USER=user
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=5432

  celery:
    build: .
    container_name: credit_celery
    command: celery -A core worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    # --- FIX IS HERE ---
    # Add the same environment variables as the web service
    environment:
      - DB_NAME=credit_db
      - DB_USER=user
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data: